devoxx/MyDevoxxGluon

src/main/java/com/gluonhq/otn/model/BaseService.java
src/main/java/com/gluonhq/otn/model/Service.java
src/main/java/com/gluonhq/otn/views/ActivityFeedPresenter.java

Added a button in the selector. When clicked upon, it will show the schedule
Note that Conference is still an inner class of a View class. Should probably move to the model package.

Add country name to conference

---

build.gradle
src/main/java/com/devoxx/DevoxxApplication.java
src/main/java/com/devoxx/model/BaseService.java
src/main/java/com/devoxx/model/DevoxxService.java
src/main/java/com/devoxx/model/Service.java
src/main/java/com/devoxx/model/cloudlink/CloudLinkService.java
src/main/java/com/devoxx/util/DevoxxNotifications.java
src/main/java/com/devoxx/util/DevoxxSettings.java
src/main/java/com/devoxx/views/helper/LoginPrompter.java
src/main/java/com/devoxx/views/helper/SessionVisuals.java

Implemented the authentication flow with Gluon CloudLink. This enables marking sessions as favorite and scheduling sessions, as well as storing session notes and voting.
All Gluon Mobile components have been updated to their latest version.

Implement authentication flow

---

DevoxxClientMobile/src/android/java/com/gluonhq/wearable/android/service/WearService.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxView.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/util/DevoxxNotifications.java
DevoxxClientMobile/src/main/java/com/devoxx/util/DevoxxSearch.java
DevoxxClientMobile/src/main/java/com/devoxx/util/ImageCache.java
DevoxxClientMobile/src/main/java/com/devoxx/util/Strings.java

@johanvos @erwin1 Please review

Improvements to Mobile client

---

.gitignore
DevoxxClientCommon/src/main/java/com/devoxx/model/Tag.java
DevoxxClientCommon/src/main/java/com/devoxx/model/Talk.java
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/views/SessionPresenter.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css

Show audience level and tags on session details view

---

DevoxxClientMobile/src/main/resources/com/devoxx/views/badge.fxml

This PR disables TextFields in Badge view so as to avoid users from selecting the text.

TextFields in Badge view must be disabled.

---

DevoxxClientCommon/src/main/java/com/devoxx/model/ProposalTypes.java
DevoxxClientCommon/src/main/java/com/devoxx/model/Tracks.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/FilterSessionsPresenter.java

Tracks and Proposal Types are wrapped in a JSON object and not returned as a JSON Array.

tracks and proposal types are wrapped in a json object

---

DevoxxClientMobile/src/main/java/com/devoxx/views/helper/FilterSessionsPresenter.java

This PR enables the filter to be active only when the current device date is in between the conference's start and end date. Otherwise, it shows all the sessions.

DEVOXX-174 Smart filter in Sessions Overview

---

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientMobile/src/main/java/com/devoxx/views/SessionsPresenter.java

Show a different message as placeholder when a filter is applied and no session matches the criteria.

DEVOXX-174 Add a filter message as placeholder

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Sponsor.java
DevoxxClientCommon/src/main/java/com/devoxx/util/SponsorCategory.java
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorsPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/SponsorCell.java

Adds the missing categories to the list of Sponsor categories

Fix sponsor list to consider all categories

---

DevoxxClientMobile/build.gradle
DevoxxClientMobile/src/main/java/com/devoxx/views/ExhibitionMapPresenter.java

- Also bump maps version (as includes some bug fixes)

Issue #62: Improve zooming over exhibition maps

---

DevoxxClientMobile/src/main/java/com/devoxx/views/SessionsPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css

This PR adds track id beside each session cell

#49 Add track color to session cells

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Favorites.java
DevoxxClientCommon/src/main/java/com/devoxx/model/ProposalTypes.java
DevoxxClientCommon/src/main/java/com/devoxx/model/Tracks.java
DevoxxClientMobile/build.gradle
DevoxxClientMobile/src/android/java/com/gluonhq/wearable/android/service/WearService.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorPresenter.java
DevoxxClientMobile/src/main/resources/sessions.json
DevoxxClientMobile/src/main/resources/speaker.json
DevoxxClientMobile/src/main/resources/speakers.json

This PR contains changes to help run the application without cloudlink config files. It also contains improvements to code by replacing listeners with event handlers wherever possible.

 Add support to load sessions and speakers from local json files 

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Speaker.java
DevoxxClientMobile/src/main/java/com/devoxx/control/DataLabel.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SessionPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SpeakerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/Util.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css

This PR removes the delay while loading session speakers in AvatarPane. Also adds some minor performance improvement to SpeakerPresenter.

#86 asynchronous load of speaker details

---

DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css

This fixes #83 - line wrap problem for list items in session catalogue

Add a new Label to ListTile for more than 3 lines of text.

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Session.java
DevoxxClientMobile/build.gradle
DevoxxClientMobile/src/main/java/com/devoxx/views/SessionsPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SpeakerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios_notch.css

This is how the SessionsPresenter looks with the header:
Fixes #68

Show session type above group of presentations

---

DevoxxClientMobile/src/main/java/com/devoxx/views/ExhibitionMapPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/ETagImageTask.java

ExhibitionPresenter shows an INDETERMINATE progress bar while the image is loaded in the background.
Fixes #105

#105 ExhibitionPresenter should show a ProgressBar

---

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorsPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/Placeholder.java

Fixes #109 and lays a foundation for improving placeholders for other views

#109 Sponsor list view should show progress bar

---

DevoxxClientMobile/src/main/java/com/devoxx/views/ConfSelectorPresenter.java
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios_notch.css

Added padding on iOS to ConferenceSelector view

---

DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios_notch.css
DevoxxClientMobile/src/main/resources/com/devoxx/voxxed.css

Please check the below image for new swatch details:
Fixes #128

Update swatch when a Voxxed event is selected

---

DevoxxClientMobile/src/main/java/com/devoxx/views/ConfSelectorPresenter.java

Always show Devoxx conferences when conferences view is shown

---

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java

Update properties to include generic messages

---

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

reload must be triggered irrespective of the contents of the notification

All silent notification should trigger reload

---

DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

Deletes all cached files from previous version of the app
Fixes #113

Delete cached files from old version

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Conference.java
DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

Use Conference data to show/hide MyBadges view

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Badge.java
DevoxxClientCommon/src/main/java/com/devoxx/model/SponsorBadge.java
DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/views/AttendeeBadgePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/SponsorCell.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/Util.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxClientMobile/src/main/resources/com/devoxx/views/sponsorbadge.fxml

SponsorBadge(s) are now device dependent

Remove authentication from Sponsors.

---

DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/retrievesessions/SessionsLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/retrievesessions/SessionsRetriever.java

Changes the Lambda function to include breaks in sessions list.

Add breaks to list of sessions

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Break.java
DevoxxClientCommon/src/main/java/com/devoxx/model/Room.java
DevoxxClientCommon/src/main/java/com/devoxx/model/Session.java
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SessionsPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SpeakerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/SessionTrack.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/SessionVisuals.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/retrievesessions/SessionsLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/retrievesessions/SessionsRetriever.java

This PR adds registration and breaks in Content Catalogue.

Show breaks in Content Catalogue

---

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

The app crashes without the fix

Return false if Session list is empty

---

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

This PR adds an alert if email is not shared via using one of the social logins.

Show Alert if social login doesn't share email id

---

DevoxxClientMobile/src/main/java/com/devoxx/DevoxxView.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SearchPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/SearchCell.java

This PR incorporate changes for creating a new ScheduleCell in Search. It also makes Search view skip view-stack.

Fix Search functionality

---

DevoxxRemoteFunctions/build.gradle
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conference/ConferenceLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conference/ConferenceRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/ConferencesLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/ConferencesRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/FutureConferencesLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/PastConferencesLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/ConferenceUtil.java

Contains AWS lambda functions to retrieve:
* All future conferences
* All past conferences
* Conference details using the conference id

#221 AWS Lambda functions related to conferences

---

DevoxxClientCommon/src/main/java/com/devoxx/filter/TimePeriod.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/Filter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/FilterSessionsPresenter.java

This PR uses the private storage to store filter options in a json file - "filter.json". The file stores an array of Filter objects.

#218 Persist all filter options

---

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/AllConferencesLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/ConferencesLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/ConferencesRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/PastConferencesLambda.java

This is an improvement to per-existing system where future and past conferences were using 2 different RFs.
With this change both can use one RF and supply a parameter to differentiate the calls.

#221 Update Lambda to retrieve conferences using user defined param

---

DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java

#229 Show share button when returned from badge detail view

---

DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java

SponsorBadge CLV should be initialized once

---

DevoxxClientCommon/src/main/java/com/devoxx/model/SponsorBadge.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java

Adds timestamp to sponsor badge

#236 Include badge-scan timestamp in sponsor badges

---

DevoxxClientMobile/src/main/java/com/devoxx/views/AttendeeBadgePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/BadgePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/BadgeCell.java

This PR fixes an issue where scanned badges weren't saved after first scan.

#233 Save all scanned badges

---

DevoxxClientMobile/src/main/java/com/devoxx/views/BadgePresenter.java

Do not use Timeline to save badge when changes are made to badge details

#233 Do not use Timeline to save badge

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Conference.java
DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java
DevoxxClientMobile/src/main/java/com/devoxx/util/JsonToObject.java
DevoxxClientMobile/src/main/java/com/devoxx/views/AboutPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ConferenceCell.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxRemoteFunctions/build.gradle
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conference/ConferenceLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conference/ConferenceRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conferences/ConferencesRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsRetriever.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/ConferenceUtil.java

This PR contain changes made to the client and the various lambda functions to support new API. 
The client now works with both old and new API conferences.

 #241 Align the application with new rest services

---

DevoxxClientMobile/build.gradle
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsRetriever.java

This is a continuation of PR #244.
The PR does the following:
* Adds Android 64-bit support
* Update talk details directly from schedules
* Drawer item should be removed when floor plans are either `null` or `empty`.

#241 Android 64-bit support and more

---

DevoxxClientCommon/src/main/java/com/devoxx/model/User.java
DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties
DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties
DevoxxClientMobile/build.gradle
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/DevoxxView.java
DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java
DevoxxClientMobile/src/main/java/com/devoxx/util/Strings.java
DevoxxClientMobile/src/main/java/com/devoxx/views/AuthenticatePresenter.java
DevoxxClientMobile/src/main/java/com/devoxx/views/VotePresenter.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxClientMobile/src/main/resources/com/devoxx/views/authenticate.fxml
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsRetriever.java

The following requests can now be made via the app:
* Favorite sessions
* Vote for a session

#241 Adds ability for requests which need authentication

---

DevoxxClientMobile/src/main/java/com/devoxx/util/JsonToObject.java

This PR also removes usage of streams from client code

Add AcceptedTalks to Speaker 

---

DevoxxClientMobile/src/main/java/com/devoxx/views/AuthenticatePresenter.java

Register and Reset password needs the cfpURL without the "api" at the end.

#241 Fix URLs for register and forget password

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Session.java
DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
DevoxxClientMobile/src/main/java/com/devoxx/views/helper/SessionVisuals.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsRetriever.java

In the new endpoint, totalFavourite count can be fetched from Session endpoint.

Favourite count can be fetched from Session data

---

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java

Sponsors still use need the conferenceId from the initial conferences list.

Use conferenceId from the conferences list for sponsors

---

DevoxxClientCommon/src/main/java/com/devoxx/model/Conference.java
DevoxxClientMobile/src/main/java/com/devoxx/views/VenuePresenter.java
DevoxxClientMobile/src/main/resources/com/devoxx/common.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_android.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios.css
DevoxxClientMobile/src/main/resources/com/devoxx/devoxx_ios_notch.css
DevoxxClientMobile/src/main/resources/com/devoxx/views/venue.fxml
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/ConferenceUtil.java

For new cfp, we fetch the location details from conference.

#241 Fix location for new cfp

---

DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/conference/ConferenceLambda.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/ConferenceUtil.java
DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/FloorPlansRetriever.java

Add floor plans to conference with cfp.dev endpoints

Enable floor plans for conferences with cfp.dev endpoints
