src/android/AndroidManifest.xml, src/ios/Default-Info.plist
The identifier `com.devoxx` is already in use by the "My Devoxx" Android application. I renamed the package name for Android and the CFBundleIdentifier for iOS to `com.devoxx.mobile` instead.
=> Change identifier names for Android and iOS apps

settings.gradle
The name of the parent folder is by default the name of the project. However, to make sure the IPA for iOS can be built consistently everywhere, we need a fixed name, as the name of the project must match the CFBundleExecutable key.
=> Set a fixed project name

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ScheduleCell.java
The following is a screenshot of how the change affects the ui:
=> #54 Add end time in session overview

DevoxxClientMobile/src/main/java/com/devoxx/views/SearchPresenter.java
Contains the following improvements:
* AppBar nav icon should be a back button
* Search TextField should receive focus when CLEAR is tapped
* Clear the TextField when search view hides
Fixes #97
=> #97 Improvements to Search view

DevoxxClientMobile/src/main/java/com/devoxx/util/DevoxxNotifications.java
This PR fixes the issue #96 related to local notifications being delivered, but when tapping they only opened the application, for both Android and iOS.
To properly work on iOS, this fix depends on a pending [PR](https://bitbucket.org/gluon-oss/charm-down/pull-requests/55/down-113-required-changes-in-local/diff) for Charm Down.
While this fix doesn't depend on #123, when the Android target is bumped to 26, we will need the mentioned Charm Down PR and adding the maven google repository (directly or via jfxmobile plugin).
=> Fix to perform notification actions

DevoxxClientCommon/src/main/java/com/devoxx/model/Conference.java, DevoxxClientCommon/src/main/java/com/devoxx/util/DevoxxSettings.java, DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java, DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/views/SessionsPresenter.java, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ConferenceCell.java, DevoxxClientMobile/src/main/java/com/devoxx/views/helper/Util.java, DevoxxClientMobile/src/main/java/com/devoxx/views/layer/ConferenceLoadingLayer.java, DevoxxClientMobile/src/main/resources/com/devoxx/common.css, DevoxxClientMobile/src/main/resources/com/devoxx/common_tablet.css
This PR introduces a conference loading layer which is shown when a conference is selected by the user. The layer will hide itself either when loading of sessions is completed or timeout of 20 seconds has reached.
Fixes #135
=> Add a conference loading layer

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/views/ConfSelectorPresenter.java
This PR creates uses a new RF from GCL to fetch all the conferences so as to not interfere with current functionality.
=> Use a new RF to fetch all conferences

DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
This PR fixes share functionality in mobile where it used to fail when the Documents directory was not present.
=> Create public storage directory if it doesn't exist

DevoxxClientMobile/src/main/java/com/devoxx/views/helper/ETagImageTask.java
All new image files are first appended with ".incomplete". Once the stream completes downloading and writing them to the private storage, ".incomplete" is removed from the file name.
When the application is run again, this allows us to check the file name and test whether the download was complete last time.
=> #169 Introduce a renaming caching stream

DevoxxClientCommon/src/main/java/com/devoxx/model/Rating.java, DevoxxClientCommon/src/main/java/com/devoxx/model/RatingData.java, DevoxxClientMobile/src/main/java/com/devoxx/DevoxxView.java, DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java, DevoxxClientMobile/src/main/java/com/devoxx/views/LeaderboardPresenter.java, DevoxxClientMobile/src/main/java/com/devoxx/views/VotePresenter.java, DevoxxClientMobile/src/main/resources/com/devoxx/views/vote.properties, DevoxxClientMobile/src/main/resources/com/devoxx/views/vote_fr.properties
Rating image and text are fetched from GCL RF (currently with mock data)
=> Disable leaderboard and remote rating data

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java, DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java
This helps fix NPE caused by the list getting assigned to the CLV before the data list has finished initialization.
=> Assign sponsor badge list once data fetch is complete

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java
After removal of ScheduledSession, it is redundant to have `functionPrefix` parameter.
=> Remove redundant method parameter

DevoxxClientCommon/src/main/java/com/devoxx/model/AudienceLevel.java, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties, DevoxxClientMobile/src/main/java/com/devoxx/views/SessionPresenter.java
Audience level is returned as BEGINNER, INTERMEDIATE, ADVANCED and EXPERT instead of L1, L2 and L3.
This PR adjusts the client according to the data returned.
=> #241 AudienceLevel should support the new data format

DevoxxClientCommon/src/main/java/com/devoxx/model/SponsorBadge.java, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties, DevoxxClientMobile/src/main/java/com/devoxx/DevoxxDrawerPresenter.java, DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/BadgeCell.java, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/SponsorBadgeCell.java, DevoxxClientMobile/src/main/resources/com/devoxx/common.css
Once the badges are scanned, a new sync option is displayed on the badge to show is a badge is yet to be synced with the backend.
If during the scan, the device fails to send the the badge to the backend, a listener is attached to the connectivity service so as to automatically sync the badge once the connectivity is back.
A sync button is also added to the SponsorBadges view to enable to enable a sponsor to manually sync all pending badges.
=> Add option to sync sponsor badges

DevoxxClientMobile/src/main/java/com/devoxx/views/BadgePresenter.java
Sync property is set to false whenever the badge scanner edits the details property triggering  re-sync or the badge with the back-end.
=> sync property should be updated whenever details change

DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java
`DeviceService#getModel` returns:
```
Build.MODEL + " ("+ Build.MANUFACTURER + ")"
```
Therefore, we need to switch the check from `startsWith` to `contains`.
=> Fix device check to load sans style

DevoxxClientMobile/src/main/java/com/devoxx/views/SponsorBadgePresenter.java, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/SponsorBadgeCell.java, DevoxxClientMobile/src/main/resources/com/devoxx/common.css
Replace not-sync icon with cell background color for showing badges that haven't been synced with the server yet.
=> #251 Background color should show sync status

DevoxxClientCommon/src/main/resources/com/devoxx/devoxx.properties, DevoxxClientCommon/src/main/resources/com/devoxx/devoxx_fr.properties, DevoxxClientMobile/src/main/java/com/devoxx/DevoxxApplication.java, DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxClientMobile/src/main/java/com/devoxx/service/Service.java, DevoxxClientMobile/src/main/java/com/devoxx/views/cell/ConferenceCell.java, DevoxxClientMobile/src/main/java/com/devoxx/views/layer/ConferenceLoadingLayer.java
In case the "conference" RF fails, we do the following:
* switch to CONF_SELECTOR view
* hide ConferenceLoading layer
* show an alert to the user
* clear conference details from local storage when alert is closed
=> #265 Show Alert message when conference RF fails

DevoxxClientMobile/src/main/java/com/devoxx/service/DevoxxService.java, DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/util/ConferenceUtil.java
Fix cfp url matching by appending "/api" to the regular expression.
This will help cfp url to not match cases like: `https://cfp.devoxx.ma/api`.
Fixes #267
=> Append regex with "/api" to improve url matching

DevoxxRemoteFunctions/build.gradle, DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsLambda.java, DevoxxRemoteFunctions/src/main/java/com/gluonhq/devoxx/serverless/sessions/SessionsRetriever.java
Talk summary in new cfp.dev endpoints contain html tags in them. For mobile app, we need to remove these tags.
=> Remove html tags and escaped characters from talk summary

DevoxxClientMobile/src/main/java/com/devoxx/views/AuthenticatePresenter.java
The toast should be shown irrespective of whether a failureRunnable exists.
=> When authentication fails, show Toast 

DevoxxRemoteFunctions/build.gradle
This PR helps to update AWS lambda directly from the command line using Gradle tasks.
For this we need to create an AWS credentials file containing the values for aws access key and secret access key. The same can be found here: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
=> Update lambda functions via Gradle tasks
